from pathlib import Path

p = Path('sources/channel-tree/ChannelTree.cpp')
s = p.read_text()
old = '''void ChannelTree::openChannel (QString channelID)\n{\n\tauto it = channelToItemMap.find (channelID);\n\tif (it == channelToItemMap.end() || it.value().isEmpty()) {\n\t\tqDebug() << "openChannel " << channelID << ": channel not found";\n\t\treturn;\n\t}\n\n    QTreeWidgetItem* item = it.value().front();\n'''
new = '''void ChannelTree::openChannel (QString channelID)\n{\n\tauto it = channelToItemMap.find (channelID);\n    QTreeWidgetItem* item = nullptr;\n\n    if (it != channelToItemMap.end() && !it.value().isEmpty()) {\n        item = it.value().front();\n    } else if (backendForSidebar) {\n        BackendChannel* personal = backendForSidebar->getStorage().getDirectChannelByUserId(\n            backendForSidebar->getLoginUser().id);\n        if (personal && personal->id == channelID) {\n            // Programmatic navigation (permalinks, Saved/Search results, etc.)\n            // must resolve the self-DM even when its ordinary server row is\n            // absent or suppressed in Favorites. Prefer the currently selected\n            // team's Personal row, otherwise use the first available one.\n            QTreeWidgetItem* current = currentItem();\n            QTreeWidgetItem* teamItem = current;\n            while (teamItem && teamItem->parent()) {\n                teamItem = teamItem->parent();\n            }\n            if (teamItem && teamItem->data(0, ItemKindRole).toInt() == TeamItemKind) {\n                item = personalItemForTeam(teamItem->data(0, ItemTeamIdRole).toString());\n            }\n            if (!item) {\n                for (auto teamIt = teamToItemMap.cbegin(); teamIt != teamToItemMap.cend(); ++teamIt) {\n                    item = personalItemForTeam(teamIt.key());\n                    if (item) {\n                        break;\n                    }\n                }\n            }\n        }\n    }\n\n    if (!item) {\n        qDebug() << "openChannel " << channelID << ": channel not found";\n        return;\n    }\n\n'''
if old not in s:
    raise SystemExit('openChannel block not found')
p.write_text(s.replace(old, new, 1))
