from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text()
    if text.count(old) != 1:
        raise SystemExit(f"{path}: expected one anchor, found {text.count(old)}")
    p.write_text(text.replace(old, new, 1))


replace_once(
    "sources/chat-area/ChatLogWidget.cpp",
    """    sourceConnections.push_back(connect(postSource, &AbstractPostSource::bodyAvailabilityChanged,\n                                        this, [this](int first, int last, bool available) {\n        qCDebug(lcTimelineTrace).nospace()\n            << \"SOURCE_BODY_AVAILABILITY list=\" << static_cast<const void*>(this)\n            << \" source=\" << sourceName(postSource)\n            << \" range=[\" << first << ',' << last << ']'\n            << \" available=\" << available;\n        setRangeAvailable(first, last, available);\n        if (available) {\n            restoreNavigationTarget();\n        }\n    }));\n""",
    """    sourceConnections.push_back(connect(postSource, &AbstractPostSource::bodyAvailabilityChanged,\n                                        this, [this](int first, int last, bool bodyAvailable) {\n        qCDebug(lcTimelineTrace).nospace()\n            << \"SOURCE_BODY_AVAILABILITY list=\" << static_cast<const void*>(this)\n            << \" source=\" << sourceName(postSource)\n            << \" range=[\" << first << ',' << last << ']'\n            << \" available=\" << bodyAvailable;\n        setRangeAvailable(first, last, bodyAvailable);\n        if (bodyAvailable) {\n            restoreNavigationTarget();\n        }\n    }));\n""",
)

replace_once(
    "sources/backend/PostRepositoryCachePolicy.cpp",
    """qint64 configuredMemoryChannelHorizonMs()\n{\n    static const qint64 value = std::max<qint64>(\n        MinuteMs,\n        QSettings().value(POST_CACHE_MEMORY_CHANNEL_IDLE_MINUTES,\n                          POST_CACHE_MEMORY_CHANNEL_IDLE_MINUTES_DEFAULT).toLongLong()\n            * MinuteMs);\n    return value;\n}\n\nqint64 configuredDiskChannelHorizonMs()\n{\n    static const qint64 value = std::max<qint64>(\n        HourMs,\n        QSettings().value(POST_CACHE_DISK_CHANNEL_IDLE_HOURS,\n                          POST_CACHE_DISK_CHANNEL_IDLE_HOURS_DEFAULT).toLongLong()\n            * HourMs);\n    return value;\n}\n""",
    """qint64 configuredMemoryChannelHorizonMs()\n{\n    return std::max<qint64>(\n        MinuteMs,\n        QSettings().value(POST_CACHE_MEMORY_CHANNEL_IDLE_MINUTES,\n                          POST_CACHE_MEMORY_CHANNEL_IDLE_MINUTES_DEFAULT).toLongLong()\n            * MinuteMs);\n}\n\nqint64 configuredDiskChannelHorizonMs()\n{\n    return std::max<qint64>(\n        HourMs,\n        QSettings().value(POST_CACHE_DISK_CHANNEL_IDLE_HOURS,\n                          POST_CACHE_DISK_CHANNEL_IDLE_HOURS_DEFAULT).toLongLong()\n            * HourMs);\n}\n""",
)

replace_once(
    "sources/widgets/LongListWidget.cpp",
    """void LongListWidget::onSliderMoved(int value)\n{\n    // sliderMoved is emitted only for interactive thumb movement. The first\n    // move immediately gives the user authority over the viewport, even before\n    // sliderReleased publishes the final viewport state.\n    releaseViewportLock(true);\n\n    const int target = logicalTargetForScrollValue(value);\n    if (target < 0) {\n        return;\n    }\n    if (!seekActive || target != seekTarget) {\n        ++seekGeneration;\n        seekTarget = target;\n    }\n    seekActive = true;\n    seekTimer.start(seekDebounceInterval);\n}\n""",
    """void LongListWidget::onSliderMoved(int value)\n{\n    // sliderMoved is emitted only for interactive thumb movement. The first\n    // move immediately gives the user authority over the viewport, even before\n    // sliderReleased publishes the final viewport state.\n    releaseViewportLock(true);\n\n    const int target = logicalTargetForScrollValue(value);\n    if (target < 0) {\n        return;\n    }\n\n    // A thumb drag inside already concrete data is ordinary scrolling. In\n    // particular, do not turn a one-pixel move near the bottom into a seek that\n    // recentres the newest post and snaps the scrollbar back to the end. The\n    // same rule also lets a small fully-resident chat materialize a new viewport\n    // immediately instead of flashing an empty seek window.\n    const Range viewportDesired = desiredRangeForViewport();\n    bool viewportBodiesReady = viewportDesired.isValid();\n    if (viewportBodiesReady) {\n        for (int index = viewportDesired.first; index <= viewportDesired.last; ++index) {\n            if (!available.testBit(index)) {\n                viewportBodiesReady = false;\n                break;\n            }\n        }\n    }\n    if (materialized.contains(target) || viewportBodiesReady) {\n        clearSeek();\n        scheduleSync(RequestReason::Scroll);\n        return;\n    }\n\n    if (!seekActive || target != seekTarget) {\n        ++seekGeneration;\n        seekTarget = target;\n    }\n    seekActive = true;\n    seekTimer.start(seekDebounceInterval);\n}\n""",
)

replace_once(
    "sources/widgets/LongListWidget.cpp",
    """int LongListWidget::logicalTargetForScrollValue(int value) const\n{\n    if (logicalCount <= 0) {\n        return -1;\n    }\n    const QScrollBar* bar = verticalScrollBar();\n    if (logicalCount == 1 || bar->maximum() <= bar->minimum()) {\n        return 0;\n    }\n    value = std::max(bar->minimum(), std::min(value, bar->maximum()));\n    const long double fraction = static_cast<long double>(value - bar->minimum())\n        / static_cast<long double>(bar->maximum() - bar->minimum());\n    return std::max(0, std::min(logicalCount - 1,\n        static_cast<int>(std::llround(fraction * (logicalCount - 1)))));\n}\n""",
    """int LongListWidget::logicalTargetForScrollValue(int value) const\n{\n    if (logicalCount <= 0) {\n        return -1;\n    }\n\n    // Scrollbar values represent the viewport's top content offset, not a post\n    // ordinal. Map the centre of that viewport through the height index so the\n    // bottom scrollbar position targets the centre of the last visible rows\n    // rather than always targeting the final logical item.\n    const qint64 top = contentOffsetForScrollValue(value);\n    const qint64 center = std::min<qint64>(\n        std::max<qint64>(0, heights.totalHeight() - 1),\n        top + std::max(0, viewport()->height() / 2));\n    return heights.indexAtPixel(center);\n}\n""",
)

replace_once(
    "sources/widgets/LongListWidget.cpp",
    """void LongListWidget::evictOutside(const Range& keepRange, int preferredCenter)\n{\n    Q_UNUSED(preferredCenter)\n    const QVector<int> current = materializedIndices();\n    for (int index : current) {\n        if (keepRange.contains(index)) {\n            continue;\n        }\n        QWidget* widget = materialized.take(index);\n        if (!widget) {\n            continue;\n        }\n        widgetIndexes.remove(widget);\n        widget->removeEventFilter(this);\n        destroyItemWidget(index, widget);\n    }\n}\n""",
    """void LongListWidget::evictOutside(const Range& keepRange, int preferredCenter)\n{\n    // maxMaterializedItems is a residency budget, not the size of the current\n    // viewport window. Keep already-created widgets while there is budget so\n    // short chats and nearby back-scrolls never churn rows unnecessarily.\n    int excess = static_cast<int>(materialized.size()) - maxMaterializedItems;\n    if (excess <= 0) {\n        return;\n    }\n\n    QVector<int> candidates;\n    const QVector<int> current = materializedIndices();\n    candidates.reserve(current.size());\n    for (int index : current) {\n        if (!keepRange.contains(index)) {\n            candidates.push_back(index);\n        }\n    }\n    std::sort(candidates.begin(), candidates.end(),\n              [preferredCenter](int lhs, int rhs) {\n        const int lhsDistance = lhs < preferredCenter\n            ? preferredCenter - lhs : lhs - preferredCenter;\n        const int rhsDistance = rhs < preferredCenter\n            ? preferredCenter - rhs : rhs - preferredCenter;\n        return lhsDistance > rhsDistance;\n    });\n\n    for (int index : candidates) {\n        if (excess <= 0) {\n            break;\n        }\n        QWidget* widget = materialized.take(index);\n        if (!widget) {\n            continue;\n        }\n        widgetIndexes.remove(widget);\n        widget->removeEventFilter(this);\n        destroyItemWidget(index, widget);\n        --excess;\n    }\n}\n""",
)

replace_once(
    "tests/LongListWidgetTest.cpp",
    """    void delayedRowGrowthKeepsStickyBottom()\n""",
    """    void visitedRowsStayMaterializedUntilBudgetIsReached()\n    {\n        TestLongListWidget list;\n        list.resize(480, 180);\n        list.setDefaultItemHeight(60);\n        list.setMaterializationLimit(200);\n        list.setItemCount(21);\n        list.setRangeAvailable(0, 20);\n        list.show();\n        settleEvents();\n\n        for (int index = 0; index < 21; ++index) {\n            list.scrollToIndex(index, Mattermost::LongListWidget::Alignment::Center);\n            settleEvents(4);\n        }\n\n        QCOMPARE(list.materializedCount(), 21);\n    }\n\n    void tinyThumbDragInsideResidentWindowDoesNotSnapToEnd()\n    {\n        TestLongListWidget list;\n        list.resize(480, 240);\n        list.setDefaultItemHeight(60);\n        list.setMaterializationLimit(200);\n        list.setSeekDebounceMs(0);\n        list.setItemCount(21);\n        list.setRangeAvailable(0, 20);\n        list.show();\n        settleEvents();\n        list.scrollToEnd();\n        settleEvents();\n\n        QScrollBar* bar = list.verticalScrollBar();\n        QVERIFY(bar->maximum() > 1);\n        const int draggedValue = bar->maximum() - 1;\n\n        bar->setSliderDown(true);\n        bar->setValue(draggedValue);\n        QVERIFY(QMetaObject::invokeMethod(bar, \"sliderMoved\",\n                                          Qt::DirectConnection,\n                                          Q_ARG(int, draggedValue)));\n        settleEvents(12);\n\n        QCOMPARE(bar->value(), draggedValue);\n        const auto visible = list.visibleRange();\n        QVERIFY(visible.isValid());\n        for (int index = visible.first; index <= visible.last; ++index) {\n            QVERIFY2(list.itemWidget(index) != nullptr,\n                     \"A fully available small chat must not expose an empty viewport during thumb drag\");\n        }\n        bar->setSliderDown(false);\n    }\n\n    void delayedRowGrowthKeepsStickyBottom()\n""",
)
