from pathlib import Path


def replace_once(text: str, old: str, new: str, name: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{name}: expected one match, found {count}")
    return text.replace(old, new, 1)


cpp_path = Path("sources/chat-area/ChannelPostSource.cpp")
cpp = cpp_path.read_text()

old = '''    oldestBoundaryProbeInFlight = true;\n    oldestBoundaryNonEmptyPage = -1;\n    oldestBoundaryEmptyPage = -1;\n    oldestBoundaryProbeStep = initialBoundaryProbePages();\n\n    const int page = pageForIndex(0);\n    const int offset = page * ServerPageSize;\n    qCDebug(lcTimelineChannel).nospace()\n        << "OLDEST_BOUNDARY_INITIAL page=" << page\n        << " offset=" << offset\n        << " step=" << oldestBoundaryProbeStep\n        << " perPage=1";\n'''
new = '''    oldestBoundaryProbeInFlight = true;\n    oldestBoundaryNonEmptyPage = -1;\n    oldestBoundaryEmptyPage = -1;\n    oldestBoundaryProbeStep = initialBoundaryProbePages();\n    oldestBoundarySearchLimitPage = pageForIndex(0);\n\n    // Large channels start at the expected deletion distance instead of first\n    // spending a round trip on the estimated oldest page. If this probe finds\n    // data, binary search walks outward towards the estimate; if it is empty,\n    // exponential stepping continues inward. The 3% value affects latency only.\n    const int page = std::max(0,\n                              oldestBoundarySearchLimitPage - oldestBoundaryProbeStep);\n    const int offset = page * ServerPageSize;\n    qCDebug(lcTimelineChannel).nospace()\n        << "OLDEST_BOUNDARY_INITIAL page=" << page\n        << " offset=" << offset\n        << " limit=" << oldestBoundarySearchLimitPage\n        << " step=" << oldestBoundaryProbeStep\n        << " perPage=1";\n'''
cpp = replace_once(cpp, old, new, "initial probe setup")

old = '''            if (exists) {\n                // The estimate reached real data, so turn the cheap validation\n                // into useful materialization. A short page proves the exact\n                // oldest boundary; a full page is still the best first block for\n                // the requested top viewport.\n                guard->oldestBoundaryNonEmptyPage = page;\n                guard->loadOldestBoundaryPage(page);\n                return;\n            }\n\n            guard->oldestBoundaryEmptyPage = page;\n            guard->probeOldestBoundary();\n'''
new = '''            if (exists) {\n                guard->oldestBoundaryNonEmptyPage = page;\n            } else {\n                guard->oldestBoundaryEmptyPage = page;\n            }\n            guard->probeOldestBoundary();\n'''
cpp = replace_once(cpp, old, new, "initial probe result")

old = '''    oldestBoundaryProbeInFlight = true;\n    oldestBoundaryNonEmptyPage = -1;\n    oldestBoundaryEmptyPage = emptyPage;\n    oldestBoundaryProbeStep = initialBoundaryProbePages();\n    probeOldestBoundary();\n'''
new = '''    oldestBoundaryProbeInFlight = true;\n    oldestBoundaryNonEmptyPage = -1;\n    oldestBoundaryEmptyPage = emptyPage;\n    oldestBoundaryProbeStep = initialBoundaryProbePages();\n    oldestBoundarySearchLimitPage = -1;\n    probeOldestBoundary();\n'''
cpp = replace_once(cpp, old, new, "reactive probe setup")

old = '''    // If the 3% heuristic is only one page, materializing the candidate block\n    // is cheaper than maintaining a separate probe phase. Likewise, once binary\n    // search leaves at most one unknown page, fetch the page immediately before\n    // the known empty boundary. It either proves the boundary or shrinks it by\n    // one page, and the payload is useful to the top viewport/prefetch window.\n    if ((oldestBoundaryNonEmptyPage < 0 && oldestBoundaryProbeStep == 1)\n        || (oldestBoundaryNonEmptyPage >= 0\n            && oldestBoundaryEmptyPage - oldestBoundaryNonEmptyPage <= 2)) {\n        if (oldestBoundaryNonEmptyPage < 0) {\n            oldestBoundaryProbeStep = 2;\n        }\n        loadOldestBoundaryPage(std::max(0, oldestBoundaryEmptyPage - 1));\n        return;\n    }\n\n    int page = -1;\n    if (oldestBoundaryNonEmptyPage < 0) {\n        page = std::max(0, oldestBoundaryEmptyPage - oldestBoundaryProbeStep);\n        oldestBoundaryProbeStep = std::min(oldestBoundaryEmptyPage + 1,\n                                           oldestBoundaryProbeStep * 2);\n    } else {\n        page = oldestBoundaryNonEmptyPage\n            + (oldestBoundaryEmptyPage - oldestBoundaryNonEmptyPage) / 2;\n    }\n'''
new = '''    // If the 3% heuristic is only one page, materializing the candidate block\n    // is cheaper than maintaining a separate probe phase. Once binary search\n    // leaves at most one unknown page, materialize the known non-empty page\n    // first: if it is short, the boundary is proved without probing that last\n    // unknown page. A full page then needs at most the one adjacent page.\n    if ((oldestBoundaryNonEmptyPage < 0 && oldestBoundaryProbeStep == 1)\n        || (oldestBoundaryNonEmptyPage >= 0 && oldestBoundaryEmptyPage >= 0\n            && oldestBoundaryEmptyPage - oldestBoundaryNonEmptyPage <= 2)) {\n        if (oldestBoundaryNonEmptyPage < 0) {\n            oldestBoundaryProbeStep = 2;\n            loadOldestBoundaryPage(std::max(0, oldestBoundaryEmptyPage - 1));\n        } else {\n            loadOldestBoundaryPage(oldestBoundaryNonEmptyPage);\n        }\n        return;\n    }\n\n    int page = -1;\n    if (oldestBoundaryNonEmptyPage >= 0 && oldestBoundaryEmptyPage < 0) {\n        // The initial 3% probe found data. Search outward towards the estimated\n        // oldest page without assuming that estimate is empty. If all probes\n        // exist, the estimated page itself is finally materialized normally.\n        if (oldestBoundarySearchLimitPage < 0\n            || oldestBoundaryNonEmptyPage >= oldestBoundarySearchLimitPage) {\n            loadOldestBoundaryPage(oldestBoundaryNonEmptyPage);\n            return;\n        }\n        page = oldestBoundaryNonEmptyPage\n            + (oldestBoundarySearchLimitPage - oldestBoundaryNonEmptyPage + 1) / 2;\n    } else if (oldestBoundaryNonEmptyPage < 0) {\n        page = std::max(0, oldestBoundaryEmptyPage - oldestBoundaryProbeStep);\n        oldestBoundaryProbeStep = std::min(oldestBoundaryEmptyPage + 1,\n                                           oldestBoundaryProbeStep * 2);\n    } else {\n        page = oldestBoundaryNonEmptyPage\n            + (oldestBoundaryEmptyPage - oldestBoundaryNonEmptyPage) / 2;\n    }\n'''
cpp = replace_once(cpp, old, new, "probe selection")

old = '''            if (exists) {\n                guard->oldestBoundaryNonEmptyPage = std::max(\n                    guard->oldestBoundaryNonEmptyPage, page);\n            } else {\n                guard->oldestBoundaryEmptyPage = std::min(\n                    guard->oldestBoundaryEmptyPage, page);\n            }\n            guard->probeOldestBoundary();\n'''
new = '''            if (exists) {\n                guard->oldestBoundaryNonEmptyPage = std::max(\n                    guard->oldestBoundaryNonEmptyPage, page);\n            } else if (guard->oldestBoundaryEmptyPage < 0) {\n                guard->oldestBoundaryEmptyPage = page;\n            } else {\n                guard->oldestBoundaryEmptyPage = std::min(\n                    guard->oldestBoundaryEmptyPage, page);\n            }\n            guard->probeOldestBoundary();\n'''
cpp = replace_once(cpp, old, new, "probe result")

old = '''            if (result.postIds.isEmpty()) {\n                if (guard->oldestBoundaryEmptyPage < 0) {\n                    guard->oldestBoundaryEmptyPage = page;\n                } else {\n                    guard->oldestBoundaryEmptyPage = std::min(\n                        guard->oldestBoundaryEmptyPage, page);\n                }\n                if (guard->oldestBoundaryNonEmptyPage >= page) {\n                    guard->oldestBoundaryNonEmptyPage = -1;\n                }\n                guard->probeOldestBoundary();\n                return;\n            }\n'''
new = '''            if (result.postIds.isEmpty()) {\n                if (guard->oldestBoundaryEmptyPage < 0) {\n                    guard->oldestBoundaryEmptyPage = page;\n                } else {\n                    guard->oldestBoundaryEmptyPage = std::min(\n                        guard->oldestBoundaryEmptyPage, page);\n                }\n                if (guard->oldestBoundaryNonEmptyPage >= page) {\n                    guard->oldestBoundaryNonEmptyPage = -1;\n                }\n                if (guard->oldestBoundaryNonEmptyPage >= 0\n                    && guard->oldestBoundaryEmptyPage\n                        == guard->oldestBoundaryNonEmptyPage + 1) {\n                    guard->reconcileRootCount(\n                        guard->oldestBoundaryEmptyPage * ServerPageSize);\n                    guard->finishOldestBoundaryProbe();\n                    return;\n                }\n                guard->probeOldestBoundary();\n                return;\n            }\n'''
cpp = replace_once(cpp, old, new, "full-page empty result")

old = '''            guard->placePage(page, result.postIds);\n            if (guard->oldestBoundaryEmptyPage == page + 1) {\n                guard->reconcileRootCount((page + 1) * ServerPageSize);\n                guard->finishOldestBoundaryProbe();\n                return;\n            }\n\n            // A proactive top check can reach a full estimated oldest page\n            // without having an independently proven empty page after it. The\n            // block is still useful materialization; avoid inventing boundary\n            // evidence from the approximate count itself.\n            if (guard->oldestBoundaryEmptyPage < 0) {\n                guard->finishOldestBoundaryProbe();\n                return;\n            }\n            guard->probeOldestBoundary();\n'''
new = '''            guard->placePage(page, result.postIds);\n            if (guard->oldestBoundaryEmptyPage == page + 1) {\n                guard->reconcileRootCount((page + 1) * ServerPageSize);\n                guard->finishOldestBoundaryProbe();\n                return;\n            }\n            if (guard->oldestBoundaryEmptyPage == page + 2) {\n                guard->loadOldestBoundaryPage(page + 1);\n                return;\n            }\n\n            // The outward search can reach a full estimated oldest page\n            // without ever observing an empty page. That means the estimate was\n            // usable as-is; the block is already useful materialization.\n            if (guard->oldestBoundaryEmptyPage < 0) {\n                guard->finishOldestBoundaryProbe();\n                return;\n            }\n            guard->probeOldestBoundary();\n'''
cpp = replace_once(cpp, old, new, "full-page continuation")

old = '''    oldestBoundaryNonEmptyPage = -1;\n    oldestBoundaryEmptyPage = -1;\n    oldestBoundaryProbeStep = 1;\n'''
new = '''    oldestBoundaryNonEmptyPage = -1;\n    oldestBoundaryEmptyPage = -1;\n    oldestBoundaryProbeStep = 1;\n    oldestBoundarySearchLimitPage = -1;\n'''
cpp = replace_once(cpp, old, new, "probe reset")

cpp_path.write_text(cpp)

h_path = Path("sources/chat-area/ChannelPostSource.h")
h = h_path.read_text()
old = '''    int oldestBoundaryNonEmptyPage = -1;\n    int oldestBoundaryEmptyPage = -1;\n    int oldestBoundaryProbeStep = 1;\n    std::vector<std::function<void()>> oldestBoundaryWaiters;\n'''
new = '''    int oldestBoundaryNonEmptyPage = -1;\n    int oldestBoundaryEmptyPage = -1;\n    int oldestBoundaryProbeStep = 1;\n    int oldestBoundarySearchLimitPage = -1;\n    std::vector<std::function<void()>> oldestBoundaryWaiters;\n'''
h = replace_once(h, old, new, "header state")
h_path.write_text(h)

doc_path = Path("docs/long-list-architecture.md")
doc = doc_path.read_text()
old = '''For a large top-edge request the source does not first download guessed ten-post pages. It validates\nthe estimated oldest page with `per_page=1`; if that page is empty, the first inward step is a heuristic\n3% of the estimated root count, rounded to ten-post pages. This ratio affects latency only; correctness\ndoes not depend on it. If the 3% distance is no larger than one page, the normal ten-post path is used\ninstead because a small channel is cheap to materialize. If the 3% probe is still empty, the step grows\nexponentially until data brackets the boundary, then binary search refines it.\n\nNear the end of binary search, when at most one unknown ten-post page remains, the source fetches the\npage immediately before the known empty boundary with `per_page=10`. A short result proves the exact\noldest boundary immediately; a full result adjacent to the empty page proves an exact multiple of ten;\nand an empty result moves the boundary one page inward. In every case any returned posts are already\nuseful viewport/prefetch materialization. The phantom logical prefix is removed once the exact count is\nknown and normal ten-post paging continues. No identity cursor is introduced by this reconciliation path.\n'''
new = '''For a large top-edge request the source does not spend a first round trip validating the estimated\noldest page. Its first one-root probe jumps inward by a heuristic 3% of the estimated root count,\nrounded to ten-post pages. This ratio affects latency only; correctness does not depend on it. If that\nprobe is empty, the step grows exponentially farther inward until data is found. If it already finds\ndata, binary search walks outward towards the estimated oldest page without assuming that estimate is\nempty; the estimated page itself is fetched only if the search actually reaches it. If the 3% distance\nis no larger than one page, the normal ten-post path is used instead because a small channel is cheap\nto materialize.\n\nNear the end of binary search, when at most one unknown ten-post page remains, the source first fetches\nthe known non-empty page with `per_page=10`. A short result proves the exact oldest boundary immediately.\nIf it is full, at most the one adjacent candidate page remains; that page either supplies useful data or\nproves an exact multiple-of-ten boundary. In every case returned posts are already useful viewport/\nprefetch materialization. The phantom logical prefix is removed once the exact count is known and normal\nten-post paging continues. No identity cursor is introduced by this reconciliation path.\n'''
doc = replace_once(doc, old, new, "architecture docs")
doc_path.write_text(doc)

# Do not leave delivery helpers in the PR.
Path("tune-oldest-boundary-search.py").unlink(missing_ok=True)
Path(".github/workflows/tune-oldest-boundary-search.yml").unlink(missing_ok=True)
